
  name: Build bicep file

  on:
  # run it on push to the default repository branch
    push:
      branches: 
        - 'bicep**'
  
  
  jobs:
    deploy:
      name: Build and Deploy Bicep
      runs-on:  ubuntu-latest
      steps:
          - name: Azure Login
            uses: azure/login@v2
            with:
              creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'
      
          - name: Checkout
            uses: actions/checkout@v1
          
          - name: Bicep Build
            uses: aliencube/bicep-build-actions@v0.3
            with:
              # List of .bicep files to build, delimited by a space. eg) file1 file2 file3 ...
              files: BICEP_DEMO/rg.bicep BICEP_DEMO/rg.bicep
              # Version of the bicep CLI. It can be the exact version (eg. `v0.3.255`), wildcard (eg. `v0.3.x`) or `latest`. If omitted, `latest` is set as default.
              version: 'latest'

          - name: Azure CLI script
            uses: azure/cli@v2
            with:
              azcliversion: 2.30.0
              inlineScript: |
                          az deployment sub create --location eastus --template-file ./BICEP_DEMO/rg.bicep && \
                          az deployment group create --resource-group azurebootcamp --template-file ./BICEP_DEMO/main.bicep
       
        
            
